-- MySQL Script generated by MySQL Workbench
-- Thu Nov 24 15:32:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ssafy_pjt
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ssafy_pjt` ;

-- -----------------------------------------------------
-- Schema ssafy_pjt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ssafy_pjt` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ssafy_pjt` ;

-- -----------------------------------------------------
-- Table `ssafy_pjt`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafy_pjt`.`user` (
  `user_id` BIGINT NOT NULL,
  `create_time` DATETIME(6) NULL DEFAULT NULL,
  `modified_date` DATETIME(6) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `role` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `UK_ob8kqyqqgmefl0aco34akdtpe` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ssafy_pjt`.`board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafy_pjt`.`board` (
  `board_id` BIGINT NOT NULL,
  `create_time` DATETIME(6) NULL DEFAULT NULL,
  `modified_date` DATETIME(6) NULL DEFAULT NULL,
  `board_type` INT NULL DEFAULT NULL,
  `content` VARCHAR(255) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `user_user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`board_id`),
  INDEX `FKriw8y6gykjkn84f0do9gijom0` (`user_user_id` ASC) VISIBLE,
  CONSTRAINT `FKriw8y6gykjkn84f0do9gijom0`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `ssafy_pjt`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ssafy_pjt`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafy_pjt`.`comment` (
  `comment_id` BIGINT NOT NULL,
  `create_time` DATETIME(6) NULL DEFAULT NULL,
  `modified_date` DATETIME(6) NULL DEFAULT NULL,
  `content` VARCHAR(255) NULL DEFAULT NULL,
  `board_id` BIGINT NULL DEFAULT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`comment_id`),
  INDEX `FKlij9oor1nav89jeat35s6kbp1` (`board_id` ASC) VISIBLE,
  INDEX `FK8kcum44fvpupyw6f5baccx25c` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK8kcum44fvpupyw6f5baccx25c`
    FOREIGN KEY (`user_id`)
    REFERENCES `ssafy_pjt`.`user` (`user_id`),
  CONSTRAINT `FKlij9oor1nav89jeat35s6kbp1`
    FOREIGN KEY (`board_id`)
    REFERENCES `ssafy_pjt`.`board` (`board_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ssafy_pjt`.`dong_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafy_pjt`.`dong_code` (
  `dong_code` VARCHAR(255) NOT NULL,
  `dong_name` VARCHAR(255) NULL DEFAULT NULL,
  `gugun_name` VARCHAR(255) NULL DEFAULT NULL,
  `sido_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`dong_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ssafy_pjt`.`house_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafy_pjt`.`house_info` (
  `apt_code` BIGINT NOT NULL,
  `apartment_name` VARCHAR(255) NULL DEFAULT NULL,
  `bonbun` VARCHAR(255) NULL DEFAULT NULL,
  `bubun` VARCHAR(255) NULL DEFAULT NULL,
  `build_year` INT NOT NULL,
  `dong` VARCHAR(255) NULL DEFAULT NULL,
  `eubmyundong_code` VARCHAR(255) NULL DEFAULT NULL,
  `jibun` VARCHAR(255) NULL DEFAULT NULL,
  `land_code` VARCHAR(255) NULL DEFAULT NULL,
  `lat` VARCHAR(255) NULL DEFAULT NULL,
  `lng` VARCHAR(255) NULL DEFAULT NULL,
  `road_name` VARCHAR(255) NULL DEFAULT NULL,
  `road_name_basement_code` VARCHAR(255) NULL DEFAULT NULL,
  `road_name_bonbun` VARCHAR(255) NULL DEFAULT NULL,
  `road_name_bubun` VARCHAR(255) NULL DEFAULT NULL,
  `road_name_code` VARCHAR(255) NULL DEFAULT NULL,
  `road_name_seq` VARCHAR(255) NULL DEFAULT NULL,
  `sigungu_code` VARCHAR(255) NULL DEFAULT NULL,
  `dong_code_dong_code` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`apt_code`),
  INDEX `FKry7stb4ctnl084mdpu2laqpya` (`dong_code_dong_code` ASC) VISIBLE,
  CONSTRAINT `FKry7stb4ctnl084mdpu2laqpya`
    FOREIGN KEY (`dong_code_dong_code`)
    REFERENCES `ssafy_pjt`.`dong_code` (`dong_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ssafy_pjt`.`favorite_house`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafy_pjt`.`favorite_house` (
  `favorite_house_id` BIGINT NOT NULL,
  `create_time` DATETIME(6) NULL DEFAULT NULL,
  `modified_date` DATETIME(6) NULL DEFAULT NULL,
  `house_info_apt_code` BIGINT NULL DEFAULT NULL,
  `user_user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`favorite_house_id`),
  INDEX `FKr2a0snuke0ryi832nfvb35lcm` (`house_info_apt_code` ASC) VISIBLE,
  INDEX `FKpek7b2nr44083o9mppf3be9bp` (`user_user_id` ASC) VISIBLE,
  CONSTRAINT `FKpek7b2nr44083o9mppf3be9bp`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `ssafy_pjt`.`user` (`user_id`),
  CONSTRAINT `FKr2a0snuke0ryi832nfvb35lcm`
    FOREIGN KEY (`house_info_apt_code`)
    REFERENCES `ssafy_pjt`.`house_info` (`apt_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ssafy_pjt`.`hibernate_sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafy_pjt`.`hibernate_sequence` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ssafy_pjt`.`house_deal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafy_pjt`.`house_deal` (
  `house_deal_id` BIGINT NOT NULL,
  `area` VARCHAR(255) NULL DEFAULT NULL,
  `cancel_deal_type` VARCHAR(255) NULL DEFAULT NULL,
  `deal_amount` VARCHAR(255) NULL DEFAULT NULL,
  `deal_day` INT NOT NULL,
  `deal_month` INT NOT NULL,
  `deal_year` INT NOT NULL,
  `floor` VARCHAR(255) NULL DEFAULT NULL,
  `apt_code` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`house_deal_id`),
  INDEX `FK3linmu4el2bomrev4dq1e1yfs` (`apt_code` ASC) VISIBLE,
  CONSTRAINT `FK3linmu4el2bomrev4dq1e1yfs`
    FOREIGN KEY (`apt_code`)
    REFERENCES `ssafy_pjt`.`house_info` (`apt_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ssafy_pjt`.`visit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafy_pjt`.`visit` (
  `visit_id` BIGINT NOT NULL,
  `board_board_id` BIGINT NULL DEFAULT NULL,
  `user_user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`visit_id`),
  INDEX `FK67pbudefmq573lc32724afvuo` (`board_board_id` ASC) VISIBLE,
  INDEX `FKrj0bg5nhb4udg6a9c8lhgrxoh` (`user_user_id` ASC) VISIBLE,
  CONSTRAINT `FK67pbudefmq573lc32724afvuo`
    FOREIGN KEY (`board_board_id`)
    REFERENCES `ssafy_pjt`.`board` (`board_id`),
  CONSTRAINT `FKrj0bg5nhb4udg6a9c8lhgrxoh`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `ssafy_pjt`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
