spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ssafy
    password: ssafy
    url: jdbc:mysql://localhost:3306/ssafy_pjt
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
  main:
    allow-bean-definition-overriding: true
#  secret-key: test